//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rug.Osc.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rug.Osc.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address string may not be null or empty.
        /// </summary>
        internal static string Address_NullOrEmpty {
            get {
                return ResourceManager.GetString("Address_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported arguemnt type &apos;{0}&apos;.
        /// </summary>
        internal static string Arguments_UnsupportedType {
            get {
                return ResourceManager.GetString("Arguments_UnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid bundle message length.
        /// </summary>
        internal static string Bundle_InvalidBundleMessageLength {
            get {
                return ResourceManager.GetString("Bundle_InvalidBundleMessageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid bundle ident &apos;{0}&apos;.
        /// </summary>
        internal static string Bundle_InvalidIdent {
            get {
                return ResourceManager.GetString("Bundle_InvalidIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid bundle message header.
        /// </summary>
        internal static string Bundle_InvalidMessageHeader {
            get {
                return ResourceManager.GetString("Bundle_InvalidMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid bundle timestamp &apos;{0}&apos;.
        /// </summary>
        internal static string Bundle_InvalidTimestamp {
            get {
                return ResourceManager.GetString("Bundle_InvalidTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing bundle ident.
        /// </summary>
        internal static string Bundle_MissingIdent {
            get {
                return ResourceManager.GetString("Bundle_MissingIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;{{&apos;. Found &apos;{0}&apos;.
        /// </summary>
        internal static string Bundle_MissingOpenBracket {
            get {
                return ResourceManager.GetString("Bundle_MissingOpenBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid container address &apos;{0}&apos;.
        /// </summary>
        internal static string Container_IsValidContainerAddress {
            get {
                return ResourceManager.GetString("Container_IsValidContainerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown osc packet type &apos;{0}&apos;.
        /// </summary>
        internal static string Listener_UnknownOscPacketType {
            get {
                return ResourceManager.GetString("Listener_UnknownOscPacketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a midi message &apos;{0}&apos;.
        /// </summary>
        internal static string MidiMessage_NotAMidiMessage {
            get {
                return ResourceManager.GetString("MidiMessage_NotAMidiMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot match 2 address patterns.
        /// </summary>
        internal static string OscAddress_CannotMatch2AddressPatterns {
            get {
                return ResourceManager.GetString("OscAddress_CannotMatch2AddressPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot match non literal address parts.
        /// </summary>
        internal static string OscAddress_CannotMatchNonLiteral {
            get {
                return ResourceManager.GetString("OscAddress_CannotMatchNonLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address &apos;{0}&apos; is not a valid osc address.
        /// </summary>
        internal static string OscAddress_NotAValidOscAddress {
            get {
                return ResourceManager.GetString("OscAddress_NotAValidOscAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected match.
        /// </summary>
        internal static string OscAddress_UnexpectedMatch {
            get {
                return ResourceManager.GetString("OscAddress_UnexpectedMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown address part &apos;{0}&apos;.
        /// </summary>
        internal static string OscAddress_UnknownAddressPart {
            get {
                return ResourceManager.GetString("OscAddress_UnknownAddressPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} channel has a value of {1}, color channel values must be in the range {2} to {3}.
        /// </summary>
        internal static string OscColor_ChannelInvalidValue {
            get {
                return ResourceManager.GetString("OscColor_ChannelInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is empty.
        /// </summary>
        internal static string Parser_ArgumentEmpty {
            get {
                return ResourceManager.GetString("Parser_ArgumentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of message while parsing argument &apos;{0}&apos;.
        /// </summary>
        internal static string Parser_ArgumentUnexpectedEndOfMessage {
            get {
                return ResourceManager.GetString("Parser_ArgumentUnexpectedEndOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address.
        /// </summary>
        internal static string Parser_InvalidAddress {
            get {
                return ResourceManager.GetString("Parser_InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid blob string length.
        /// </summary>
        internal static string Parser_InvalidBlobStringLength {
            get {
                return ResourceManager.GetString("Parser_InvalidBlobStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid color &apos;{0}&apos;.
        /// </summary>
        internal static string Parser_InvalidColor {
            get {
                return ResourceManager.GetString("Parser_InvalidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while parsing an osc packet.
        /// </summary>
        internal static string Parser_InvalidPacket {
            get {
                return ResourceManager.GetString("Parser_InvalidPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The packet length is not the correct size.
        /// </summary>
        internal static string Parser_InvalidSegmentLength {
            get {
                return ResourceManager.GetString("Parser_InvalidSegmentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed array &apos;{0}&apos;.
        /// </summary>
        internal static string Parser_MalformedArrayArgument {
            get {
                return ResourceManager.GetString("Parser_MalformedArrayArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed object &apos;{0}&apos;.
        /// </summary>
        internal static string Parser_MalformedObjectArgument {
            get {
                return ResourceManager.GetString("Parser_MalformedObjectArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed object &apos;{0}&apos;, missing type name.
        /// </summary>
        internal static string Parser_MalformedObjectArgument_MissingType {
            get {
                return ResourceManager.GetString("Parser_MalformedObjectArgument_MissingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed string argument &apos;{0}&apos; .
        /// </summary>
        internal static string Parser_MalformedStringArgument {
            get {
                return ResourceManager.GetString("Parser_MalformedStringArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed type tag.
        /// </summary>
        internal static string Parser_MalformedTypeTag {
            get {
                return ResourceManager.GetString("Parser_MalformedTypeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address was empty.
        /// </summary>
        internal static string Parser_MissingAddressEmpty {
            get {
                return ResourceManager.GetString("Parser_MissingAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address terminator could not be found.
        /// </summary>
        internal static string Parser_MissingAddressTerminator {
            get {
                return ResourceManager.GetString("Parser_MissingAddressTerminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminator could not be found while parsing argument &apos;{0}&apos;.
        /// </summary>
        internal static string Parser_MissingArgumentTerminator {
            get {
                return ResourceManager.GetString("Parser_MissingArgumentTerminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;]&apos;.
        /// </summary>
        internal static string Parser_MissingArrayEndChar {
            get {
                return ResourceManager.GetString("Parser_MissingArrayEndChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comma found.
        /// </summary>
        internal static string Parser_MissingComma {
            get {
                return ResourceManager.GetString("Parser_MissingComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;}&apos;.
        /// </summary>
        internal static string Parser_MissingObjectEndChar {
            get {
                return ResourceManager.GetString("Parser_MissingObjectEndChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;&quot;&apos;.
        /// </summary>
        internal static string Parser_MissingStringEndChar {
            get {
                return ResourceManager.GetString("Parser_MissingStringEndChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type tag terminator could not be found.
        /// </summary>
        internal static string Parser_MissingTypeTag {
            get {
                return ResourceManager.GetString("Parser_MissingTypeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of message.
        /// </summary>
        internal static string Parser_UnexpectedEndOfMessage {
            get {
                return ResourceManager.GetString("Parser_UnexpectedEndOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown argument type &apos;{0}&apos; on argument &apos;{1}&apos;.
        /// </summary>
        internal static string Parser_UnknownArgumentType {
            get {
                return ResourceManager.GetString("Parser_UnknownArgumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown object type &apos;{0}&apos;.
        /// </summary>
        internal static string Parser_UnknownObjectType {
            get {
                return ResourceManager.GetString("Parser_UnknownObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while waiting for a message.
        /// </summary>
        internal static string Receiver_ErrorWhileWaitingForMessage {
            get {
                return ResourceManager.GetString("Receiver_ErrorWhileWaitingForMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The suppied address must be a multicast address.
        /// </summary>
        internal static string Receiver_NotMulticastAddress {
            get {
                return ResourceManager.GetString("Receiver_NotMulticastAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The receiver socket has been disconnected.
        /// </summary>
        internal static string Receiver_SocketIsClosed {
            get {
                return ResourceManager.GetString("Receiver_SocketIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both local and remote must belong to the same address family.
        /// </summary>
        internal static string Socket_AddressFamilyIncompatible {
            get {
                return ResourceManager.GetString("Socket_AddressFamilyIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The socket is already open or is not fully closed.
        /// </summary>
        internal static string Socket_AlreadyOpenOrNotClosed {
            get {
                return ResourceManager.GetString("Socket_AlreadyOpenOrNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The valid range for local port numbers is 1 to 65535 or 0 for a dynamically assigned port.
        /// </summary>
        internal static string Socket_LocalPortOutOfRange {
            get {
                return ResourceManager.GetString("Socket_LocalPortOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The valid range for port numbers is 1 to 65535.
        /// </summary>
        internal static string Socket_PortOutOfRange {
            get {
                return ResourceManager.GetString("Socket_PortOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The valid range for remote port numbers is 1 to 65535.
        /// </summary>
        internal static string Socket_RemotePortOutOfRange {
            get {
                return ResourceManager.GetString("Socket_RemotePortOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported address family &apos;{0}&apos;.
        /// </summary>
        internal static string Socket_UnsupportedAddressFamily {
            get {
                return ResourceManager.GetString("Socket_UnsupportedAddressFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid osc-timetag string &apos;{0}&apos;.
        /// </summary>
        internal static string TimeTag_InvalidString {
            get {
                return ResourceManager.GetString("TimeTag_InvalidString", resourceCulture);
            }
        }
    }
}
